http:
  serversTransports:
    insecure:
      insecureSkipVerify: true

  routers:
    thoth:
      entryPoints:
        - "https"
      rule: "Host(`thoth.local.ilghost.party`)"
      middlewares:
        - default-headers
      tls: &cloudflare_tls
        certResolver: cloudflare
        domains:
          - main: local.ilghost.party
            sans:
              - "*.local.ilghost.party"
      service: thoth
    truenas:
      entryPoints:
        - "https"
      rule: "Host(`truenas.local.ilghost.party`)"
      middlewares:
        - default-headers
      tls: *cloudflare_tls
      service: truenas
    victorialogs:
      entryPoints:
        - "https"
      rule: "Host(`victorialogs.local.ilghost.party`)"
      middlewares:
        - default-headers
      tls: *cloudflare_tls
      service: victorialogs
    victoriametrics:
      entryPoints:
        - "https"
      rule: "Host(`victoriametrics.local.ilghost.party`)"
      middlewares:
        - default-headers
      tls: *cloudflare_tls
      service: victoriametrics

  services:
    thoth:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: "https://192.168.70.38:9090"
    truenas:
      loadBalancer:
        servers:
          - url: "http://192.168.70.11:80"
    victorialogs:
      loadBalancer:
        servers:
          - url: "http://192.168.70.11:9428"
    victoriametrics:
      loadBalancer:
        servers:
          - url: "http://192.168.70.11:8428"

  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
