http:
  routers:
    thoth:
      entryPoints:
        - "https"
      rule: "Host(`thoth.local.ilghost.party`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: &cloudflare_tls
        certResolver: cloudflare
        domains:
          - main: local.ilghost.party
            sans:
              - "*.local.ilghost.party"
      service: thoth
    truenas:
      entryPoints:
        - "https"
      rule: "Host(`truenas.local.ilghost.party`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: *cloudflare_tls
      service: truenas
    victorialogs:
      entryPoints:
        - "https"
      rule: "Host(`victorialogs.local.ilghost.party`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: *cloudflare_tls
      service: victorialogs
    victoriametrics:
      entryPoints:
        - "https"
      rule: "Host(`victoriametrics.local.ilghost.party`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: *cloudflare_tls
      service: victoriametrics

  services:
    thoth:
      loadBalancer:
        servers:
          - url: "https://192.168.70.38:9090"
        passHostHeader: true
    truenas:
      loadBalancer:
        servers:
          - url: "http://192.168.70.11:80"
        passHostHeader: true
    victorialogs:
      loadBalancer:
        servers:
          - url: "http://192.168.70.11:9428"
        passHostHeader: true
    victoriametrics:
      loadBalancer:
        servers:
          - url: "http://192.168.70.11:8428"
        passHostHeader: true

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
    default-whitelist:
      ipAllowList:
        sourceRange:
          - "192.168.0.0/16"
          - "172.16.0.0/12"
    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers
